services:
  db:
    image: postgres:16.4-bullseye
    environment:
      POSTGRES_DB: liquibase_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.29.2
    volumes:
      - ./src/main/resources/db:/liquibase/changelog
    environment:
      - LIQUIBASE_CHANGELOG_FILE=/liquibase/changelog/db.changelog-master.yaml
      - LIQUIBASE_URL=jdbc:postgresql://db:5432/liquibase_db
      - LIQUIBASE_USERNAME=postgres
      - LIQUIBASE_PASSWORD=1234
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["liquibase", "update"]

volumes:
  db-data:
