spring:
  application:
    name: demo-liquibase
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${HOSTNAME}:${PORT}/${DB_NAME}
    username: ${POSTGRES_NAME}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
server:
  port: 8168